In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import torch
import pandas as pd

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
print(device)

cuda

In [5]:
file_path_train = '/content/drive/My Drive/001.PhD/Smartphone/traintest/trainDataset2.csv'

In [6]:
df = pd.read_csv(file_path_train)

In [7]:
df.head()

                                            sequence
0  android.net.nsd.STATE_CHANGED, android.net.con...
1  android.net.nsd.STATE_CHANGED, android.net.con...
2  android.intent.action.DREAMING_STARTED, androi...
3  android.net.wifi.RSSI_CHANGED, android.intent....
4  android.intent.action.DREAMING_STARTED, androi...

In [8]:
sequence_list = df['sequence'].tolist()

In [9]:
# print(sequence_list[0])

In [10]:
sequence_list = sequence_list[:20000]
print(len(sequence_list))

20000

In [11]:
trainDataset = []
for sequence in sequence_list:
    result = sequence.split(",")
    result = [item.strip() for item in result]
    trainDataset.append(result)

In [12]:
# print(trainDataset[0])

In [13]:
# trainDataset[0][0:-1]

In [14]:
from collections import Counter

In [15]:
all_tokens = [token for seq in trainDataset for token in seq]

In [16]:
counter = Counter(all_tokens)

In [17]:
# print(counter)

In [18]:
# Vocabulary
vocab = {token: idx + 1 for idx, token in enumerate(counter.keys())}
vocab["<PAD>"] = 0

In [19]:
inv_vocab = {idx: token for token, idx in vocab.items()}
vocab_size = len(vocab)

In [20]:
print(vocab_size)

62

In [ ]:
from torch.nn.utils.rnn import pad_sequence

In [ ]:
X = []
y = []

In [ ]:
for seq in trainDataset:
    input_seq = [vocab[token] for token in seq[:-1]]
    target = vocab[seq[-1]]

    X.append(torch.tensor(input_seq))
    y.append(target)

In [ ]:
# Pad sequences
X_padded = pad_sequence(X, batch_first=True, padding_value=0)
y = torch.tensor(y)

In [ ]:
import torch.nn as nn

In [ ]:
class VanillaLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x):
        embedded = self.embedding(x)
        _, (hidden, _) = self.lstm(embedded)
        logits = self.fc(hidden[-1])  # last hidden state
        return logits

In [ ]:
model = VanillaLSTM(
    vocab_size=vocab_size,
    embed_dim=64,
    hidden_dim=128
)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

epochs = 230

for epoch in range(epochs):
    optimizer.zero_grad()

    outputs = model(X_padded)
    loss = criterion(outputs, y)

    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 1, Loss: 4.1556
Epoch 2, Loss: 4.1429
Epoch 3, Loss: 4.1304
Epoch 4, Loss: 4.1179
Epoch 5, Loss: 4.1050
Epoch 6, Loss: 4.0915
Epoch 7, Loss: 4.0768
Epoch 8, Loss: 4.0605
Epoch 9, Loss: 4.0419
Epoch 10, Loss: 4.0200
Epoch 11, Loss: 3.9932
Epoch 12, Loss: 3.9591
Epoch 13, Loss: 3.9143
Epoch 14, Loss: 3.8533
Epoch 15, Loss: 3.7682
Epoch 16, Loss: 3.6488
Epoch 17, Loss: 3.4864
Epoch 18, Loss: 3.2832
Epoch 19, Loss: 3.0624
Epoch 20, Loss: 2.8678
Epoch 21, Loss: 2.7327
Epoch 22, Loss: 2.6528
Epoch 23, Loss: 2.6053
Epoch 24, Loss: 2.5732
Epoch 25, Loss: 2.5501
Epoch 26, Loss: 2.5346
Epoch 27, Loss: 2.5264
Epoch 28, Loss: 2.5239
Epoch 29, Loss: 2.5247
Epoch 30, Loss: 2.5256
Epoch 31, Loss: 2.5240
Epoch 32, Loss: 2.5185
Epoch 33, Loss: 2.5092
Epoch 34, Loss: 2.4970
Epoch 35, Loss: 2.4832
Epoch 36, Loss: 2.4697
Epoch 37, Loss: 2.4582
Epoch 38, Loss: 2.4495
Epoch 39, Loss: 2.4434
Epoch 40, Loss: 2.4392
Epoch 41, Loss: 2.4359
Epoch 42, Loss: 2.4326
Epoch 43, Loss: 2.4291
Epoch 44, Loss: 2.4259
Epoch 45, Loss: 2.4233
Epoch 46, Loss: 2.4209
Epoch 47, Loss: 2.4182
Epoch 48, Loss: 2.4148
Epoch 49, Loss: 2.4109
Epoch 50, Loss: 2.4070
Epoch 51, Loss: 2.4024
Epoch 52, Loss: 2.3975
Epoch 53, Loss: 2.3929
Epoch 54, Loss: 2.3875
Epoch 55, Loss: 2.3818
Epoch 56, Loss: 2.3759
Epoch 57, Loss: 2.3694
Epoch 58, Loss: 2.3629
Epoch 59, Loss: 2.3562
Epoch 60, Loss: 2.3489
Epoch 61, Loss: 2.3415
Epoch 62, Loss: 2.3340
Epoch 63, Loss: 2.3257
Epoch 64, Loss: 2.3166
Epoch 65, Loss: 2.3063
Epoch 66, Loss: 2.2950
Epoch 67, Loss: 2.2824
Epoch 68, Loss: 2.2686
Epoch 69, Loss: 2.2552
Epoch 70, Loss: 2.2425
Epoch 71, Loss: 2.2294
Epoch 72, Loss: 2.2161
Epoch 73, Loss: 2.2032
Epoch 74, Loss: 2.1910
Epoch 75, Loss: 2.1781
Epoch 76, Loss: 2.1644
Epoch 77, Loss: 2.1505
Epoch 78, Loss: 2.1366
Epoch 79, Loss: 2.1221
Epoch 80, Loss: 2.1073
Epoch 81, Loss: 2.0924
Epoch 82, Loss: 2.0774
Epoch 83, Loss: 2.0623
Epoch 84, Loss: 2.0468
Epoch 85, Loss: 2.0310
Epoch 86, Loss: 2.0152
Epoch 87, Loss: 1.9992
Epoch 88, Loss: 1.9830
Epoch 89, Loss: 1.9674
Epoch 90, Loss: 1.9528
Epoch 91, Loss: 1.9386
Epoch 92, Loss: 1.9240
Epoch 93, Loss: 1.9094
Epoch 94, Loss: 1.8952
Epoch 95, Loss: 1.8812
Epoch 96, Loss: 1.8677
Epoch 97, Loss: 1.8544
Epoch 98, Loss: 1.8411
Epoch 99, Loss: 1.8273
Epoch 100, Loss: 1.8129
Epoch 101, Loss: 1.7985
Epoch 102, Loss: 1.7847
Epoch 103, Loss: 1.7709
Epoch 104, Loss: 1.7568
Epoch 105, Loss: 1.7423
Epoch 106, Loss: 1.7328
Epoch 107, Loss: 1.7252
Epoch 108, Loss: 1.7169
Epoch 109, Loss: 1.7045
Epoch 110, Loss: 1.6939
Epoch 111, Loss: 1.6831
Epoch 112, Loss: 1.6728
Epoch 113, Loss: 1.6629
Epoch 114, Loss: 1.6525
Epoch 115, Loss: 1.6416
Epoch 116, Loss: 1.6298
Epoch 117, Loss: 1.6190
Epoch 118, Loss: 1.6097
Epoch 119, Loss: 1.5996
Epoch 120, Loss: 1.5890
Epoch 121, Loss: 1.5791
Epoch 122, Loss: 1.5697
Epoch 123, Loss: 1.5604
Epoch 124, Loss: 1.5512
Epoch 125, Loss: 1.5430
Epoch 126, Loss: 1.5332
Epoch 127, Loss: 1.5243
Epoch 128, Loss: 1.5151
Epoch 129, Loss: 1.5063
Epoch 130, Loss: 1.4979
Epoch 131, Loss: 1.4892
Epoch 132, Loss: 1.4809
Epoch 133, Loss: 1.4724
Epoch 134, Loss: 1.4632
Epoch 135, Loss: 1.4550
Epoch 136, Loss: 1.4457
Epoch 137, Loss: 1.4385
Epoch 138, Loss: 1.4310
Epoch 139, Loss: 1.4239
Epoch 140, Loss: 1.4165
Epoch 141, Loss: 1.4093
Epoch 142, Loss: 1.4029
Epoch 143, Loss: 1.3966
Epoch 144, Loss: 1.3905
Epoch 145, Loss: 1.3841
Epoch 146, Loss: 1.3776
Epoch 147, Loss: 1.3713
Epoch 148, Loss: 1.3652
Epoch 149, Loss: 1.3595
Epoch 150, Loss: 1.3540
Epoch 151, Loss: 1.3487
Epoch 152, Loss: 1.3434
Epoch 153, Loss: 1.3380
Epoch 154, Loss: 1.3326
Epoch 155, Loss: 1.3273
Epoch 156, Loss: 1.3220
Epoch 157, Loss: 1.3171
Epoch 158, Loss: 1.3122
Epoch 159, Loss: 1.3072
Epoch 160, Loss: 1.3025
Epoch 161, Loss: 1.2980
Epoch 162, Loss: 1.2935
Epoch 163, Loss: 1.2892
Epoch 164, Loss: 1.2849
Epoch 165, Loss: 1.2808
Epoch 166, Loss: 1.2767
Epoch 167, Loss: 1.2727
Epoch 168, Loss: 1.2687
Epoch 169, Loss: 1.2648
Epoch 170, Loss: 1.2608
Epoch 171, Loss: 1.2568
Epoch 172, Loss: 1.2527
Epoch 173, Loss: 1.2481
Epoch 174, Loss: 1.2438
Epoch 175, Loss: 1.2399
Epoch 176, Loss: 1.2362
Epoch 177, Loss: 1.2326
Epoch 178, Loss: 1.2291
Epoch 179, Loss: 1.2254
Epoch 180, Loss: 1.2217
Epoch 181, Loss: 1.2180
Epoch 182, Loss: 1.2142
Epoch 183, Loss: 1.2104
Epoch 184, Loss: 1.2068
Epoch 185, Loss: 1.2031
Epoch 186, Loss: 1.1994
Epoch 187, Loss: 1.1958
Epoch 188, Loss: 1.1925
Epoch 189, Loss: 1.1893
Epoch 190, Loss: 1.1860
Epoch 191, Loss: 1.1828
Epoch 192, Loss: 1.1797
Epoch 193, Loss: 1.1765
Epoch 194, Loss: 1.1735
Epoch 195, Loss: 1.1704
Epoch 196, Loss: 1.1674
Epoch 197, Loss: 1.1645
Epoch 198, Loss: 1.1615
Epoch 199, Loss: 1.1586
Epoch 200, Loss: 1.1558
Epoch 201, Loss: 1.1530
Epoch 202, Loss: 1.1502
Epoch 203, Loss: 1.1475
Epoch 204, Loss: 1.1448
Epoch 205, Loss: 1.1421
Epoch 206, Loss: 1.1394
Epoch 207, Loss: 1.1368
Epoch 208, Loss: 1.1342
Epoch 209, Loss: 1.1316
Epoch 210, Loss: 1.1290
Epoch 211, Loss: 1.1263
Epoch 212, Loss: 1.1237
Epoch 213, Loss: 1.1212
Epoch 214, Loss: 1.1188
Epoch 215, Loss: 1.1164
Epoch 216, Loss: 1.1140
Epoch 217, Loss: 1.1116
Epoch 218, Loss: 1.1092
Epoch 219, Loss: 1.1069
Epoch 220, Loss: 1.1045
Epoch 221, Loss: 1.1021
Epoch 222, Loss: 1.0997
Epoch 223, Loss: 1.0973
Epoch 224, Loss: 1.0950
Epoch 225, Loss: 1.0928
Epoch 226, Loss: 1.0905
Epoch 227, Loss: 1.0883
Epoch 228, Loss: 1.0861
Epoch 229, Loss: 1.0839
Epoch 230, Loss: 1.0817

In [ ]:
file_path_test = '/content/drive/My Drive/001.PhD/Smartphone/traintest/testDataset2.csv'

In [ ]:
dfTest = pd.read_csv(file_path_test)

In [ ]:
dfTest.head()

                                            sequence
0  android.net.wifi.RSSI_CHANGED, android.intent....
1  android.intent.action.DREAMING_STARTED, androi...
2  android.intent.action.DREAMING_STOPPED, androi...
3  android.net.wifi.RSSI_CHANGED, android.intent....
4  android.net.wifi.RSSI_CHANGED, android.intent....

In [ ]:
sequence_list_test = dfTest['sequence'].tolist()

In [ ]:
sequence_list_test = sequence_list_test[:8000]

In [ ]:
testDataset = []
for sequence in sequence_list_test:
    result = sequence.split(",")
    result = [item.strip() for item in result]
    testDataset.append(result)

In [ ]:
X_test = []
y_test = []

In [ ]:
for seq in testDataset:
    # Skip sequences with unseen tokens (optional but safe)
    if any(token not in vocab for token in seq):
        continue

    input_seq = [vocab[token] for token in seq[:-1]]
    target = vocab[seq[-1]]

    X_test.append(torch.tensor(input_seq))
    y_test.append(target)

In [ ]:
X_test_padded = pad_sequence(X_test, batch_first=True, padding_value=0)
y_test = torch.tensor(y_test)

In [ ]:
model.eval()

with torch.no_grad():
    logits = model(X_test_padded)
    y_pred = torch.argmax(logits, dim=1)

In [ ]:
y_true = y_test.cpu().numpy()
y_pred = y_pred.cpu().numpy()

In [ ]:
from sklearn.metrics import precision_recall_fscore_support

In [ ]:
precision, recall, _, _ = precision_recall_fscore_support(
    y_true,
    y_pred,
    average="micro",
    zero_division=0
)

_, _, f1_macro, _ = precision_recall_fscore_support(
    y_true,
    y_pred,
    average="macro",
    zero_division=0
)

_, _, f1_weighted, _ = precision_recall_fscore_support(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

In [ ]:
print(f"Precision    : {precision:.4f}")
print(f"Recall       : {recall:.4f}")
print(f"F1 (macro)   : {f1_macro:.4f}")
print(f"F1 (weighted): {f1_weighted:.4f}")

Precision    : 0.7494
Recall       : 0.7494
F1 (macro)   : 0.1655
F1 (weighted): 0.7276